In [1]:
import geopandas as gpd
import pandas as pd
import ast
from shapely.geometry import Point
from shapely.wkt import loads

Attribute values

In [2]:
chicago = gpd.read_file('data/chicago_tract_geo.shp')
chicago_tbl1 = pd.read_csv('data/nhgis0014_ds262_20225_tract.csv', encoding='latin-1')
chicago_tbl2 = pd.read_csv('data/nhgis0014_ds263_20225_tract.csv', encoding='latin-1')
chicago_all = chicago.merge(chicago_tbl1, on='GISJOIN')
chicago_all = chicago_all.merge(chicago_tbl2, on='GISJOIN')

# age: % age < 18 or > 64
chicago["AGE"] = (sum([chicago_all["AQM4E0%s" % '{number:0{width}d}'.format(width=2, number=i)] for i in range(3, 7)]) + \
    sum([chicago_all["AQM4E0%s" % '{number:0{width}d}'.format(width=2, number=i)] for i in range(20, 26)]) + \
    sum([chicago_all["AQM4E0%s" % '{number:0{width}d}'.format(width=2, number=i)] for i in range(27, 31)]) + \
    sum([chicago_all["AQM4E0%s" % '{number:0{width}d}'.format(width=2, number=i)] for i in range(44, 50)])) / chicago_all["AQM4E001"]

# race: % non-white
chicago["RACE"] = (sum([chicago_all["AQNGE0%s" % '{number:0{width}d}'.format(width=2, number=i)] for i in range(3, 9)])) / chicago_all["AQNGE001"]

# ethnicity: % hispanic
chicago["ETH"] = chicago_all["AQNPE003"] / chicago_all["AQNPE001"]

# education: % with high school diploma or below
chicago["EDU"] = (sum([chicago_all["AQPJE0%s" % '{number:0{width}d}'.format(width=2, number=i)] for i in range(3, 12)]) + \
                  sum([chicago_all["AQPJE0%s" % '{number:0{width}d}'.format(width=2, number=i)] for i in range(20, 29)])) / chicago_all["AQPJE001"]

# language: % speaker language other than English
chicago["LAN"] = (sum([chicago_all["AQPXE0%s" % '{number:0{width}d}'.format(width=2, number=i)] for i in range(3, 15)])) / chicago_all["AQPXE001"]

# household income: % less than 45000
chicago["INC"] = (sum([chicago_all["AQP5E0%s" % '{number:0{width}d}'.format(width=2, number=i)] for i in range(2, 10)])) / chicago_all["AQP5E001"]

# computer access: % no computer
chicago["COM"] = chicago_all["AQWFE007"] / chicago_all["AQWFE001"]

# internet access: % no internet
chicago["INT"] = chicago_all["AQWGE008"] / chicago_all["AQWGE001"]

# disability: % with disability
chicago["DIS"] = (sum([chicago_all["AQ7BE0%s" % '{number:0{width}d}'.format(width=2, number=i)] for i in range(4, 21, 3)]) + \
                  sum([chicago_all["AQ7BE0%s" % '{number:0{width}d}'.format(width=2, number=i)] for i in range(23, 40, 3)])) / chicago_all["AQ7BE001"]

chicago

,GISJOIN,STATEFP,COUNTYFP,TRACTCE,GEOID,NAME,NAMELSAD,MTFCC,FUNCSTAT,ALAND,...,geometry,AGE,RACE,ETH,EDU,LAN,INC,COM,INT,DIS
0,G1700310010100,17,031,010100,17031010100,101,Census Tract 101,G5020,S,379511.0,...,"POLYGON ((684576.334 536740.727, 684575.428 53...",0.223623,0.552988,0.214753,0.226190,0.542636,0.352283,0.066753,0.077950,0.142721
1,G1700310010201,17,031,010201,17031010201,102.01,Census Tract 102.01,G5020,S,504464.0,...,"POLYGON ((683811.867 535505.497, 683805.731 53...",0.381730,0.745798,0.243971,0.406519,0.809115,0.450132,0.101057,0.097754,0.092927
2,G1700310010202,17,031,010202,17031010202,102.02,Census Tract 102.02,G5020,S,351253.0,...,"POLYGON ((684259.925 535555.750, 684224.526 53...",0.305759,0.688656,0.194066,0.308289,0.835650,0.383483,0.035159,0.065413,0.160355
3,G1700310010300,17,031,010300,17031010300,103,Census Tract 103,G5020,S,472522.0,...,"POLYGON ((684991.444 535638.821, 684973.659 53...",0.329325,0.464005,0.169312,0.257770,0.681982,0.341319,0.020348,0.077125,0.099456
4,G1700310010400,17,031,010400,17031010400,104,Census Tract 104,G5020,S,548761.0,...,"POLYGON ((685636.907 534050.741, 685623.969 53...",0.103510,0.200089,0.084507,0.081518,0.398445,0.417881,0.142857,0.142857,0.138386
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
787,G1700310843900,17,031,843900,17031843900,8439,Census Tract 8439,G5020,S,1478136.0,...,"POLYGON ((694653.395 510419.501, 694598.790 51...",0.361351,0.929730,0.034324,0.308354,0.238074,0.462063,0.084961,0.180373,0.214595
788,G1700310844600,17,031,844600,17031844600,8446,Census Tract 8446,G5020,S,434671.0,...,"POLYGON ((690255.397 513444.213, 690228.741 51...",0.245275,0.953407,0.009231,0.369839,0.562802,0.362319,0.042271,0.050725,0.151457
789,G1700310844700,17,031,844700,17031844700,8447,Census Tract 8447,G5020,S,401852.0,...,"POLYGON ((682935.003 517569.538, 682919.462 51...",0.244153,0.942955,0.205933,0.399664,0.466770,0.479134,0.054096,0.066461,0.159156
790,G1700310980000,17,031,980000,17031980000,9800,Census Tract 9800,G5020,S,19890204.0,...,"POLYGON ((663819.199 532991.108, 663843.208 53...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
791,G1700310980100,17,031,980100,17031980100,9801,Census Tract 9801,G5020,S,2981781.0,...,"POLYGON ((680928.831 509779.063, 680917.293 50...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
chicago.columns

Index(['GISJOIN', 'STATEFP', 'COUNTYFP', 'TRACTCE', 'GEOID', 'NAME',
       'NAMELSAD', 'MTFCC', 'FUNCSTAT', 'ALAND', 'AWATER', 'INTPTLAT',
       'INTPTLON', 'Shape_Leng', 'Shape_Area', 'ORIG_FID', 'geometry', 'AGE',
       'RACE', 'ETH', 'EDU', 'LAN', 'INC', 'COM', 'INT', 'DIS'],
      dtype='object')

Tech sites

In [130]:
# Read the CSV file
tech_sites = pd.read_csv('data/Public_Technology_Resources_20240705.csv', encoding='latin-1')

# Extract coordinates and convert to separate 'lat' and 'lon' columns
tech_sites['coord'] = tech_sites['LOCATION'].str.split('\n').str[2].apply(ast.literal_eval)
tech_sites['lat'] = tech_sites['coord'].apply(lambda x: x[0])
tech_sites['lon'] = tech_sites['coord'].apply(lambda x: x[1])

# Convert to GeoDataFrame by creating a geometry column with Point objects
tech_sites['geometry'] = tech_sites.apply(lambda row: Point(row['lon'], row['lat']), axis=1)
tech_sites_gdf = gpd.GeoDataFrame(tech_sites, geometry='geometry', crs=4326).to_crs(chicago.crs)

# Drop the intermediate 'coord', 'lat', and 'lon' columns if not needed
tech_sites_gdf = tech_sites_gdf.drop(columns=['coord', 'lat', 'lon'])
tech_sites_gdf.head()

,TYPE,FACILITY,STREET ADDRESS,CITY,STATE,ZIP,PHONE,WEBSITE,HOURS,APPOINTMENT,INTERNET,WIFI,TRAINING,LOCATION,geometry
0,Chicago Public Library,Dunning,7455 W. Cornelia Avenue,Chicago,IL,60634,(312) 743-0480,http://www.chipublib.org/branch/details/librar...,"M: 2PM-6PM; TU, TH: 10AM-6PM; W: 12PM-8PM; F, ...",NaN,True,True,True,"7455 W. Cornelia Avenue\nChicago, IL 60634\n(4...",POINT (673192.281 526794.356)
1,Chicago Public Library,Toman,2708 S. Pulaski Road,Chicago,IL,60623,(312) 745-1660,http://www.chipublib.org/branch/details/librar...,"M: 2PM-6PM; TU, TH: 10AM-6PM; W: 12PM-8PM; F, ...",NaN,True,True,True,"2708 S. Pulaski Road\nChicago, IL 60623\n(41.8...",POINT (681471.720 516146.739)
2,Community Technology Center,Employment Resource Center,1623 W. Howard,Chicago,IL,60626,(773) 262-3515,http://www.howardarea.org,M-F: 9AM-5PM; SA: 9AM-1PM,No,True,False,True,"1623 W. Howard\nChicago, IL 60626\n(42.0193216...",POINT (684019.429 536276.597)
3,Chicago Public Library,Albany Park,5150 N. Kimball Avenue,Chicago,IL,60625,(312) 744-1933,http://www.chipublib.org/branch/details/librar...,"M: 2PM-6PM; TU, TH: 12PM-8PM; W: 10AM-6PM; F, ...",NaN,True,True,True,"5150 N. Kimball Avenue\nChicago, IL 60625\n(41...",POINT (681074.011 531021.696)
4,Chicago Public School,Sawyer Elementary School,5248 S Sawyer Ave,Chicago,IL,60632,(773) 535-9275,http://www.sawyer.cps.k12.il.us/,Call for hours,Yes,True,True,False,"5248 S Sawyer Ave\nChicago, IL 60632\n(41.7980...",POINT (683504.628 511384.690)

In [131]:
tech_sites_gdf['TYPE'].unique()

array(['Chicago Public Library', 'Community Technology Center',
       'Chicago Public School', 'City Colleges of Chicago',
       'Senior Center', 'Business Resource Network ', 'WorkForce Center',
       'Wireless Internet Zone', 'Youth Center', 'FamilyNet Center'],
      dtype=object)

In [132]:
# Perform spatial join
tech_sites_joined = tech_sites_gdf.sjoin(chicago[['GISJOIN', 'geometry']], how='left')

# Count occurrences of OBJECTID by GISJOIN
count = tech_sites_joined.groupby('GISJOIN').size().reset_index(name='TECH_CNT')

# Merge count with chicago GeoDataFrame
chicago = chicago.merge(count, on='GISJOIN', how='left')

# Fill NaN values with 0 and convert to integer
chicago['TECH_CNT'] = chicago['TECH_CNT'].fillna(0).astype(int)
chicago

,GISJOIN,STATEFP,COUNTYFP,TRACTCE,GEOID,NAME,NAMELSAD,MTFCC,FUNCSTAT,ALAND,...,AGE,RACE,ETH,EDU,LAN,INC,COM,INT,DIS,TECH_CNT
0,G1700310010100,17,031,010100,17031010100,101,Census Tract 101,G5020,S,379511.0,...,0.223623,0.552988,0.214753,0.226190,0.542636,0.352283,0.066753,0.077950,0.142721,0
1,G1700310010201,17,031,010201,17031010201,102.01,Census Tract 102.01,G5020,S,504464.0,...,0.381730,0.745798,0.243971,0.406519,0.809115,0.450132,0.101057,0.097754,0.092927,0
2,G1700310010202,17,031,010202,17031010202,102.02,Census Tract 102.02,G5020,S,351253.0,...,0.305759,0.688656,0.194066,0.308289,0.835650,0.383483,0.035159,0.065413,0.160355,2
3,G1700310010300,17,031,010300,17031010300,103,Census Tract 103,G5020,S,472522.0,...,0.329325,0.464005,0.169312,0.257770,0.681982,0.341319,0.020348,0.077125,0.099456,1
4,G1700310010400,17,031,010400,17031010400,104,Census Tract 104,G5020,S,548761.0,...,0.103510,0.200089,0.084507,0.081518,0.398445,0.417881,0.142857,0.142857,0.138386,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
787,G1700310843900,17,031,843900,17031843900,8439,Census Tract 8439,G5020,S,1478136.0,...,0.361351,0.929730,0.034324,0.308354,0.238074,0.462063,0.084961,0.180373,0.214595,0
788,G1700310844600,17,031,844600,17031844600,8446,Census Tract 8446,G5020,S,434671.0,...,0.245275,0.953407,0.009231,0.369839,0.562802,0.362319,0.042271,0.050725,0.151457,0
789,G1700310844700,17,031,844700,17031844700,8447,Census Tract 8447,G5020,S,401852.0,...,0.244153,0.942955,0.205933,0.399664,0.466770,0.479134,0.054096,0.066461,0.159156,0
790,G1700310980000,17,031,980000,17031980000,9800,Census Tract 9800,G5020,S,19890204.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
791,G1700310980100,17,031,980100,17031980100,9801,Census Tract 9801,G5020,S,2981781.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

Max capacity

In [133]:
# libraries
libraries = pd.read_csv('data/Libraries_-_2022_Visitors_by_Location_20240706.csv', encoding='latin-1')
libraries['geometry'] = libraries['Location'].apply(loads)
libraries_gdf = gpd.GeoDataFrame(libraries, geometry='geometry', crs=4326).to_crs(chicago.crs)

# schools
schools = pd.read_csv('data/CPS_School_Locations_SY1415_20240706.csv', encoding='latin-1')
schools['geometry'] = schools['the_geom'].apply(loads)
schools_gdf = gpd.GeoDataFrame(schools, geometry='geometry', crs=4326).to_crs(chicago.crs)

# community centers
community_centers = pd.read_csv('data/Community_Service_Centers_20240706.csv', encoding='latin-1')
community_centers['coord'] = community_centers['LOCATION'].str.split('\n').str[2].apply(ast.literal_eval)
community_centers['lat'] = community_centers['coord'].apply(lambda x: x[0])
community_centers['lon'] = community_centers['coord'].apply(lambda x: x[1])
community_centers['geometry'] = community_centers.apply(lambda row: Point(row['lon'], row['lat']), axis=1)
community_centers_gdf = gpd.GeoDataFrame(community_centers, geometry='geometry', crs=4326).to_crs(chicago.crs)
community_centers_gdf = community_centers_gdf.drop(columns=['coord', 'lat', 'lon'])

# senior centers
senior_centers = pd.read_csv('data/Senior_Centers_20240706.csv', encoding='latin-1')
senior_centers['coord'] = senior_centers['LOCATION'].str.split('\n').str[2].apply(ast.literal_eval)
senior_centers['lat'] = senior_centers['coord'].apply(lambda x: x[0])
senior_centers['lon'] = senior_centers['coord'].apply(lambda x: x[1])
senior_centers['geometry'] = senior_centers.apply(lambda row: Point(row['lon'], row['lat']), axis=1)
senior_centers_gdf = gpd.GeoDataFrame(senior_centers, geometry='geometry', crs=4326).to_crs(chicago.crs)
senior_centers_gdf = senior_centers_gdf.drop(columns=['coord', 'lat', 'lon'])

# workforce centers
workforce_centers = pd.read_csv('data/Workforce_Centers_20240706.csv', encoding='latin-1')
workforce_centers['coord'] = workforce_centers['LOCATION'].str.split('\n').str[2].apply(ast.literal_eval)
workforce_centers['lat'] = workforce_centers['coord'].apply(lambda x: x[0])
workforce_centers['lon'] = workforce_centers['coord'].apply(lambda x: x[1])
workforce_centers['geometry'] = workforce_centers.apply(lambda row: Point(row['lon'], row['lat']), axis=1)
workforce_centers_gdf = gpd.GeoDataFrame(workforce_centers, geometry='geometry', crs=4326).to_crs(chicago.crs)
workforce_centers_gdf = workforce_centers_gdf.drop(columns=['coord', 'lat', 'lon'])

# family and support services
support_service = pd.read_csv('data/Family_and_Support_Services_Delegate_Agencies.csv', encoding='latin-1')
support_service['geometry'] = support_service.apply(lambda row: Point(row['Longitude'], row['Latitude']), axis=1)
support_service_gdf = gpd.GeoDataFrame(support_service, geometry='geometry', crs=4326).to_crs(chicago.crs)

In [134]:
# libraries
libraries_joined = libraries_gdf.sjoin(chicago[['GISJOIN', 'geometry']], how='left')
count = libraries_joined.groupby('GISJOIN').size().reset_index(name='LIB_CNT')
chicago = chicago.merge(count, on='GISJOIN', how='left')
chicago['LIB_CNT'] = chicago['LIB_CNT'].fillna(0).astype(int)

# schools
schools_joined = schools_gdf.sjoin(chicago[['GISJOIN', 'geometry']], how='left')
count = schools_joined.groupby('GISJOIN').size().reset_index(name='SCH_CNT')
chicago = chicago.merge(count, on='GISJOIN', how='left')
chicago['SCH_CNT'] = chicago['SCH_CNT'].fillna(0).astype(int)

# community centers
community_centers_joined = community_centers_gdf.sjoin(chicago[['GISJOIN', 'geometry']], how='left')
count = community_centers_joined.groupby('GISJOIN').size().reset_index(name='CC_CNT')
chicago = chicago.merge(count, on='GISJOIN', how='left')
chicago['CC_CNT'] = chicago['CC_CNT'].fillna(0).astype(int)

# senior centers
senior_centers_joined = senior_centers_gdf.sjoin(chicago[['GISJOIN', 'geometry']], how='left')
count = senior_centers_joined.groupby('GISJOIN').size().reset_index(name='SC_CNT')
chicago = chicago.merge(count, on='GISJOIN', how='left')
chicago['SC_CNT'] = chicago['SC_CNT'].fillna(0).astype(int)

# workforce centers
workforce_centers_joined = workforce_centers_gdf.sjoin(chicago[['GISJOIN', 'geometry']], how='left')
count = workforce_centers_joined.groupby('GISJOIN').size().reset_index(name='WC_CNT')
chicago = chicago.merge(count, on='GISJOIN', how='left')
chicago['WC_CNT'] = chicago['WC_CNT'].fillna(0).astype(int)

# family and support services
support_service_joined = support_service_gdf.sjoin(chicago[['GISJOIN', 'geometry']], how='left')
count = support_service_joined.groupby('GISJOIN').size().reset_index(name='SS_CNT')
chicago = chicago.merge(count, on='GISJOIN', how='left')
chicago['SS_CNT'] = chicago['SS_CNT'].fillna(0).astype(int)

chicago['MAX_CAP'] = chicago['LIB_CNT'] + chicago['SCH_CNT'] + chicago['CC_CNT'] + chicago['SC_CNT'] + chicago['WC_CNT'] + chicago['SS_CNT']

In [135]:
chicago = chicago.to_crs(3857)
chicago.to_file('data/chicago_tract_all.shp')

Population-weighted centroids

In [4]:
cook = gpd.read_file('data/chicago_tract.shp')
cook_block = gpd.read_file('data/cook_block.shp')
pop = pd.read_csv('data/nhgis0008_ds258_2020_block.csv', encoding='latin-1')
cook_block = cook_block.merge(pop[['GISJOIN', 'U7H001']], on='GISJOIN')

# Calculate the population-weighted center for each tract in cook_tract
tract_centers = []
for _, tract in cook.iterrows():
    blocks_in_tract = cook_block[cook_block['geometry'].within(tract['geometry'])]
    
    weighted_center = blocks_in_tract['geometry'].centroid
    weighted_population = blocks_in_tract['U7H001']

    total_weighted_population = weighted_population.sum()

    if total_weighted_population > 0:
        # Use population-weighted centroid if population is greater than 0
        weighted_longitude = (weighted_center.x * weighted_population).sum() / total_weighted_population
        weighted_latitude = (weighted_center.y * weighted_population).sum() / total_weighted_population
    else:
        # Use geometric centroid if population is 0
        weighted_longitude = tract['geometry'].centroid.x
        weighted_latitude = tract['geometry'].centroid.y

    tract_centers.append({
        'GISJOIN': tract['GISJOIN'],
        'Lon_w': weighted_longitude,
        'Lat_w': weighted_latitude
    })

tract_centers_gdf = gpd.GeoDataFrame(tract_centers, geometry=gpd.points_from_xy([center['Lon_w'] for center in tract_centers], [center['Lat_w'] for center in tract_centers]))
cook_centroids = tract_centers_gdf.merge(cook, on='GISJOIN')
cook_centroids = cook_centroids.drop('geometry_y', axis=1)
cook_centroids = cook_centroids.rename(columns={'geometry_x': 'geometry'})
cook_centroids = cook_centroids.set_geometry('geometry')
cook_centroids.crs = cook.crs
cook_centroids.to_file('data/chicago_centroids_all.shp')
cook_centroids

,GISJOIN,Lon_w,Lat_w,geometry,STATEFP,COUNTYFP,TRACTCE,GEOID,NAME,NAMELSAD,...,R3,R4,R5,R6,R7,HHI1,HHI2,HHI3,Total_Pop,Total_HH
0,G1700310010100,684221.785904,536506.549117,POINT (684221.786 536506.549),17,031,010100,17031010100,101,Census Tract 101,...,0,94,0,278,621,818,1145,359,4284,2322
1,G1700310010201,683361.585376,535848.771305,POINT (683361.585 535848.771),17,031,010201,17031010201,102.01,Census Tract 102.01,...,41,298,0,838,1937,1363,1461,204,8210,3028
2,G1700310010202,684032.517605,535872.761074,POINT (684032.518 535872.761),17,031,010202,17031010202,102.02,Census Tract 102.02,...,86,312,0,353,277,469,646,108,2865,1223
3,G1700310010300,684542.829846,535948.251783,POINT (684542.830 535948.252),17,031,010300,17031010300,103,Census Tract 103,...,76,338,0,704,303,1040,1560,447,6237,3047
4,G1700310010400,685225.899687,534657.507557,POINT (685225.900 534657.508),17,031,010400,17031010400,104,Census Tract 104,...,0,213,0,71,257,860,1065,133,4473,2058
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
787,G1700310843900,694302.110504,509607.030347,POINT (694302.111 509607.030),17,031,843900,17031843900,8439,Census Tract 8439,...,29,50,0,98,73,1017,1130,54,3700,2201
788,G1700310844600,690000.312414,513706.489801,POINT (690000.312 513706.490),17,031,844600,17031844600,8446,Census Tract 8446,...,0,0,24,15,80,300,445,83,2275,828
789,G1700310844700,682417.843484,517566.140090,POINT (682417.843 517566.140),17,031,844700,17031844700,8447,Census Tract 8447,...,0,0,0,156,151,310,308,29,1753,647
790,G1700310980000,665423.171153,530281.953343,POINT (665423.171 530281.953),17,031,980000,17031980000,9800,Census Tract 9800,...,0,0,0,0,0,0,0,0,0,0
791,G1700310980100,680418.257056,510005.601050,POINT (680418.257 510005.601),17,031,980100,17031980100,9801,Census Tract 9801,...,0,0,0,0,0,0,0,0,0,0